language: node_js
node_js:
  - v16.17.0
install:
  - npm install
services:
  - mongodb
script:
  - npm test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "cs3219-task-b"
  env: "Cs3219taskb-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-008483243369"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: main
