language: node_js
node_js:
  - v16.17.0
install:
  - npm install
services:
  - mongodb
script:
  - npm test
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: AKIAQD6NEAVURCSHZ7ZI
  secret_access_key:
    secure: 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
  region: "ap-southeast-1"
  app: "cs3219-task-b"
  env: "Cs3219taskb-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-008483243369"
